### PR TITLE
Add ctools module

### PR DESCRIPTION
**Pull request by vbouchet**

### CODE REVIEW

**Comment by vbouchet** [comment]
retest this please

**Comment by vbouchet** [comment]
retest this please

**Comment by vbouchet** [comment]
retest this please

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master PR/job/Master%20PR/15/
Test PASSed.

**Comment by vbouchet** [comment]
retest this please

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/16/
Test PASSed.

**Comment by vbouchet** [comment]
retest this please

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/17/
Test PASSed.

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/18/
Test PASSed.

**Pull request merged**
