### PR TITLE
Init custom modules

### PR DESCRIPTION
**Pull request by vtriclot**

### CODE REVIEW

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/21/
Test PASSed.

**Comment by vtriclot** [comment]
retest this please

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/22/
Test PASSed.

**Comment by vbouchet31** [comment]
retest this please

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/31/
Test PASSed.

**Pull request merged**
