### PR TITLE
Add date module

### PR DESCRIPTION
**Pull request by vbouchet**

### CODE REVIEW

**Comment by vbouchet** [comment]
retest this please

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Branch%20PR/1/
Test PASSed.

**Comment by vbouchet** [comment]
retest this please

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Branch%20PR/2/
Test PASSed.

**Pull request merged**
