### PR TITLE
Initiate a module file with some phpcs errors for testing

### PR DESCRIPTION
**Pull request by vbouchet**

### CODE REVIEW

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/36/
Test PASSed.

**Comment by vbouchet31** [comment]
retest this please

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/37/
Test FAILed.

**Comment by vbouchet31** [comment]
retest this please

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/39/

**Comment by vbouchet31** [comment]
retest this please

**Comment by vbouchet31** [comment]
!!! Couldn't read commit file !!!

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/40/

**Comment by vbouchet31** [comment]
retest this please

**Comment by vbouchet31** [comment]
!!! Couldn't read commit file !!!

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/41/

**Comment by vbouchet31** [comment]
retest this please

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

FILE: ...rkspace/docroot/sites/all/modules/custom/custom_main/custom_main.module
--------------------------------------------------------------------------------
FOUND 3 ERROR(S) AFFECTING 2 LINE(S)
--------------------------------------------------------------------------------
  7 | ERROR | Missing function doc comment
 11 | ERROR | Array indentation error, expected 4 spaces but found 3
 11 | ERROR | Do not use t() in hook_menu()
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

Time: 0 seconds, Memory: 2.25Mb


--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/42/

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/43/
Test PASSed.

**Comment by vbouchet** [comment]
retest this please

**Comment by vbouchet31** [comment]
!!! Couldn't read commit file !!!

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/44/

**Comment by vbouchet31** [comment]
!!! Couldn't read commit file !!!

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/1/

**Comment by vbouchet** [comment]
retest this please

**Comment by vbouchet31** [comment]
!!! Couldn't read commit file !!!

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/2/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/3/
Test PASSed.

**Comment by vbouchet** [comment]
retest this please

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/4/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/5/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------
ERROR: The file "/var/lib/jenkins/jobs/Master PR - Ant/workspace/src/docroot/sites/all/modules/custom/custom_main/custom_main.module" does not exist.

Usage: phpcs [-nwlsaepvi] [-d key[=value]]
    [--report=<report>] [--report-file=<reportfile>] [--report-<report>=<reportfile>] ...
    [--report-width=<reportWidth>] [--generator=<generator>] [--tab-width=<tabWidth>]
    [--severity=<severity>] [--error-severity=<severity>] [--warning-severity=<severity>]
    [--runtime-set key value] [--config-set key value] [--config-delete key] [--config-show]
    [--standard=<standard>] [--sniffs=<sniffs>] [--encoding=<encoding>]
    [--extensions=<extensions>] [--ignore=<patterns>] <file> ...
                      Set runtime value (see --config-set) 
        -n            Do not print warnings (shortcut for --warning-severity=0)
        -w            Print both warnings and errors (on by default)
        -l            Local directory only, no recursion
        -s            Show sniff codes in all reports
        -a            Run interactively
        -e            Explain a standard by showing the sniffs it includes
        -p            Show progress of the run
        -v[v][v]      Print verbose output
        -i            Show a list of installed coding standards
        -d            Set the [key] php.ini value to [value] or [true] if value is omitted
        --help        Print this help message
        --version     Print version information
        <file>        One or more files and/or directories to check
        <extensions>  A comma separated list of file extensions to check
                      (only valid if checking a directory)
        <patterns>    A comma separated list of patterns to ignore files and directories
        <encoding>    The encoding of the files being checked (default is iso-8859-1)
        <sniffs>      A comma separated list of sniff codes to limit the check to
                      (all sniffs must be part of the specified standard)
        <severity>    The minimum severity required to display an error or warning
        <standard>    The name or path of the coding standard to use
        <tabWidth>    The number of spaces each tab represents
        <generator>   The name of a doc generator to use
                      (forces doc generation instead of checking)
        <report>      Print either the "full", "xml", "checkstyle", "csv", "json"
                      "emacs", "source", "summary", "svnblame", "gitblame", "hgblame" or
                      "notifysend" report
                      (the "full" report is printed by default)
        <reportfile>  Write the report to the specified file path
        <reportWidth> How many columns wide screen reports should be printed

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/6/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

FILE: ...rkspace/docroot/sites/all/modules/custom/custom_main/custom_main.module
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 7 | ERROR | Missing function doc comment
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

Time: 0 seconds, Memory: 2.25Mb


--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/7/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

FILE: ...rkspace/docroot/sites/all/modules/custom/custom_main/custom_main.module
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 7 | ERROR | Missing function doc comment
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

Time: 0 seconds, Memory: 2.25Mb


--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/8/

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

FILE: ...rkspace/docroot/sites/all/modules/custom/custom_main/custom_main.module
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 7 | ERROR | Missing function doc comment
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

Time: 0 seconds, Memory: 2.25Mb


--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/9/

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

FILE: ...rkspace/docroot/sites/all/modules/custom/custom_main/custom_main.module
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 7 | ERROR | Missing function doc comment
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

Time: 0 seconds, Memory: 2.25Mb


--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/10/

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

FILE: ...rkspace/docroot/sites/all/modules/custom/custom_main/custom_main.module
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 7 | ERROR | Missing function doc comment
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

Time: 0 seconds, Memory: 2.25Mb


--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/11/

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

FILE: ...rkspace/docroot/sites/all/modules/custom/custom_main/custom_main.module
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 7 | ERROR | Missing function doc comment
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

Time: 0 seconds, Memory: 2.25Mb


--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/12/

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

FILE: ...rkspace/docroot/sites/all/modules/custom/custom_main/custom_main.module
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 7 | ERROR | Missing function doc comment
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

Time: 0 seconds, Memory: 2.25Mb


--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/13/

**Comment by vbouchet** [comment]
retest this please

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

FILE: ...rkspace/docroot/sites/all/modules/custom/custom_main/custom_main.module
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 7 | ERROR | Missing function doc comment
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

Time: 0 seconds, Memory: 2.25Mb


--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/14/

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/15/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/16/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/17/

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/18/

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/19/

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/20/

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/21/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/22/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/23/

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/24/

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/25/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/26/

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/27/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/28/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------
ERROR: option "-t" not known.

Usage: phpcs [-nwlsaepvi] [-d key[=value]]
    [--report=<report>] [--report-file=<reportfile>] [--report-<report>=<reportfile>] ...
    [--report-width=<reportWidth>] [--generator=<generator>] [--tab-width=<tabWidth>]
    [--severity=<severity>] [--error-severity=<severity>] [--warning-severity=<severity>]
    [--runtime-set key value] [--config-set key value] [--config-delete key] [--config-show]
    [--standard=<standard>] [--sniffs=<sniffs>] [--encoding=<encoding>]
    [--extensions=<extensions>] [--ignore=<patterns>] <file> ...
                      Set runtime value (see --config-set) 
        -n            Do not print warnings (shortcut for --warning-severity=0)
        -w            Print both warnings and errors (on by default)
        -l            Local directory only, no recursion
        -s            Show sniff codes in all reports
        -a            Run interactively
        -e            Explain a standard by showing the sniffs it includes
        -p            Show progress of the run
        -v[v][v]      Print verbose output
        -i            Show a list of installed coding standards
        -d            Set the [key] php.ini value to [value] or [true] if value is omitted
        --help        Print this help message
        --version     Print version information
        <file>        One or more files and/or directories to check
        <extensions>  A comma separated list of file extensions to check
                      (only valid if checking a directory)
        <patterns>    A comma separated list of patterns to ignore files and directories
        <encoding>    The encoding of the files being checked (default is iso-8859-1)
        <sniffs>      A comma separated list of sniff codes to limit the check to
                      (all sniffs must be part of the specified standard)
        <severity>    The minimum severity required to display an error or warning
        <standard>    The name or path of the coding standard to use
        <tabWidth>    The number of spaces each tab represents
        <generator>   The name of a doc generator to use
                      (forces doc generation instead of checking)
        <report>      Print either the "full", "xml", "checkstyle", "csv", "json"
                      "emacs", "source", "summary", "svnblame", "gitblame", "hgblame" or
                      "notifysend" report
                      (the "full" report is printed by default)
        <reportfile>  Write the report to the specified file path
        <reportWidth> How many columns wide screen reports should be printed

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/29/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

FILE: ...rkspace/docroot/sites/all/modules/custom/custom_main/custom_main.module
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 7 | ERROR | Missing function doc comment
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

Time: 1 second, Memory: 2.25Mb


--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/30/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

FILE: ...rkspace/docroot/sites/all/modules/custom/custom_main/custom_main.module
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 7 | ERROR | Missing function doc comment
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

Time: 1 second, Memory: 2.25Mb


--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/31/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

FILE: ...rkspace/docroot/sites/all/modules/custom/custom_main/custom_main.module
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 7 | ERROR | Missing function doc comment
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

Time: 1 second, Memory: 2.25Mb


--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/32/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

FILE: ...rkspace/docroot/sites/all/modules/custom/custom_main/custom_main.module
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 7 | ERROR | Missing function doc comment
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

Time: 1 second, Memory: 2.25Mb


--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/33/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

FILE: ...rkspace/docroot/sites/all/modules/custom/custom_main/custom_main.module
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 7 | ERROR | Missing function doc comment
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

Time: 1 second, Memory: 2.25Mb


--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/34/

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/35/
Test PASSed.

**Comment by vbouchet31** [comment]
Build comment file: 
--------------

--------------

Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR%20-%20Ant/36/
Test PASSed.

**Pull request merged**
