### PR TITLE
Bri 1000

### PR DESCRIPTION
**Pull request by vbouchet**

### CODE REVIEW

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/24/
Test PASSed.

**Comment by vbouchet** [comment]
restest this please

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/25/
Test PASSed.

**Comment by vbouchet** [comment]
retest this please

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/26/
Test FAILed.

**Comment by vbouchet** [comment]
retest this please

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/27/
Test FAILed.

**Comment by vbouchet** [comment]
retest this please

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/28/
Test FAILed.

**Comment by vbouchet** [comment]
restest this please

**Comment by vbouchet31** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://192.168.1.41:8080/job/Master%20PR/29/
Test FAILed.

**Pull request closed without merging**
